### ISSUE TITLE
Mentor call #3, Friday November 24

### ISSUE THREAD

**Issue by AnneKlapwijk** [nodeschool/utrecht#15]
Dear mentors, we need some help for our next workshop: [Nodeschool Utrecht #3](https://www.meetup.com/NodeSchoolUtreg/events/244649829/). Who wants to join us?

- [x] @RamonGebben
- [x] @GeorgeSapkin
- [x] @AnneKlapwijk
- [x] @rickheere
- [x] @toddmerrill
- [ ] You?

@stefanmirck @jpwesselink @daanpeer

**Comment by rickheere** [comment]
Me
