### ISSUE TITLE
Mentor call #4, Friday January 26

### ISSUE THREAD

**Issue by AnneKlapwijk** [nodeschool/utrecht#17]
Dear mentors, we could use some extra hands for the next [Nodeschool Utrecht](https://www.meetup.com/en-AU/NodeSchoolUtreg/events/246418927/). Will you help us out?

- [x] @RamonGebben
- [ ] @GeorgeSapkin
- [x] @AnneKlapwijk
- [x] @rickheere
- [x] @philiiiiiipp
- [ ] You?

@rickheere @toddmerrill @stefanmirck @jpwesselink @daanpeer

**Comment by rickheere** [comment]
Me

**Comment by philiiiiiipp** [comment]
Me can be there if needed :-)

**Comment by AnneKlapwijk** [comment]
@philiiiiiipp Great! I'll add you to the list 😄

**Comment by stefanmirck** [comment]
I won’t be able to make it. 😞
