### ISSUE TITLE
Mentor call #5, Friday February 23

### ISSUE THREAD

**Issue by AnneKlapwijk** [nodeschool/utrecht#18]
👋 Hey mentors, it's almost time for our [5th workshop](https://www.meetup.com/NodeSchoolUtreg/events/247506344/). Unfortunately, I can't be there this time because I'm on a holiday ⛷ , so we could use extra help this workshop 💪 .

- [ ] @RamonGebben
- [x] @GeorgeSapkin
- [x] @rickheere
- [x] @philiiiiiipp
- [x] @toddmerrill
- [ ] You?

@rickheere @toddmerrill @stefanmirck @jpwesselink @daanpeer @philiiiiiipp

**Comment by philiiiiiipp** [comment]
Me can. I dont know if I manage exactly 18:30 but somewhere around the time.

**Comment by AnneKlapwijk** [comment]
Awesome, thanks @philiiiiiipp !
