### ISSUE TITLE
Mentor call #6, Friday March 30

### ISSUE THREAD

**Issue by AnneKlapwijk** [nodeschool/utrecht#21]
👋 Hi mentors! 

We just announced our [6th workshop](https://www.meetup.com/NodeSchoolUtreg/events/248565784/). Unfortunately, I can't be there because I'm in Frankfurt that weekend, so we could use extra help this workshop 💪 . Are you with us?

- [x] @RamonGebben
- [x] @GeorgeSapkin
- [x] @rickheere
- [x] @alxbrg 
- [ ] You?
- [ ] You?
- [ ] You?

@toddmerrill @jpwesselink @daanpeer

**Comment by GeorgeSapkin** [comment]
@alxbrg ?

**Comment by alxbrg** [comment]
Sorry guys I didn't notice the notification apparently. I'll be there!

**Comment by philiiiiiipp** [comment]
I am in Germany.

**Comment by stefanmirck** [comment]
Sorry peeps, can’t make it. 😞 I’m running a couple of user tests on location on the 30th.
