### ISSUE TITLE
Mentor call #7, Friday April 20

### ISSUE THREAD

**Issue by AnneKlapwijk** [nodeschool/utrecht#25]
Dear mentors, 

We need some help for the [upcoming workshop](https://www.meetup.com/NodeSchoolUtreg/events/249596567/). Please let us know if you are available. 
Thanks for all your help! 💖 

- [x] @RamonGebben
- [x] @GeorgeSapkin
- [x] @AnneKlapwijk
- [x] @rickheere 
- [x] @philiiiiiipp
- [x] @toddmerrill

@toddmerrill @jpwesselink @stefanmirck @daanpeer @alxbrg

**Comment by GeorgeSapkin** [comment]
@alxbrg ?
