### ISSUE TITLE
Mentor call #8, Friday May 25

### ISSUE THREAD

**Issue by AnneKlapwijk** [nodeschool/utrecht#28]
Hi mentors 👋 , 

As always, we can use some help for the [upcoming meetup](https://www.meetup.com/NodeSchoolUtreg/events/250713003/). Are you with us?

- [x] @RamonGebben
- [x] @GeorgeSapkin
- [x] @AnneKlapwijk
- [x] @philiiiiiipp
- [x] @toddmerrill
- [ ] @rickheere 
- [ ] You?

@toddmerrill @philiiiiiipp @jpwesselink @stefanmirck @daanpeer @alxbrg

**Comment by philiiiiiipp** [comment]
I will be there

**Comment by toddmerrill** [comment]
I too shall appear
