### ISSUE TITLE
Mentor call #1, 29 September 2017

### ISSUE THREAD

**Issue by RamonGebben** [nodeschool/utrecht#9]
First edition of Nodeschool Utrecht is happening on 29th of September 2017. Like any Nodeschool we are going to need mentors. Do you want to come out and help?

- [x] @GeorgeSapkin
- [x] @RamonGebben
- [x] @AnneKlapwijk
- [x] @stefanmirck
- [ ] You?
- [ ] You?

@toddmerrill @rickheere

**Comment by AnneKlapwijk** [comment]
@RamonGebben Count me in 👍

**Comment by AnneKlapwijk** [comment]
@rickheere :bellhop_bell:

**Comment by philiiiiiipp** [comment]
I am in Germany to vote that week.

**Comment by stefanmirck** [comment]
You know I’m gonna be there!
